// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *About → Konomi Member*
 */
export interface AboutDocumentDataKonomiMemberItem {
  /**
   * Konomi Member Link field in *About → Konomi Member*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Miake Izakaya
   * - **API ID Path**: about.konomi_member[].konomi_member_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  konomi_member_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

type AboutDocumentDataSlicesSlice = never;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Page Title field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Über Konomi
   * - **API ID Path**: about.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  page_title: prismic.RichTextField;

  /**
   * Japanese Subtitles First field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: チーム [chi|mu] --
   * - **API ID Path**: about.japanese_subtitles_first
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  japanese_subtitles_first: prismic.RichTextField;

  /**
   * Japanese Subtitles Second field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: dt.: "Team"
   * - **API ID Path**: about.japanese_subtitles_second
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  japanese_subtitles_second: prismic.RichTextField;

  /**
   * About Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Yap Yap Yap
   * - **API ID Path**: about.about_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  about_description: prismic.KeyTextField;

  /**
   * Konomi Member field in *About*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.konomi_member[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  konomi_member: prismic.GroupField<
    Simplify<AboutDocumentDataKonomiMemberItem>
  >;

  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice>; /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AboutDocumentData>, "about", Lang>;

type ArchiveDocumentDataSlicesSlice = never;

/**
 * Content for Archive documents
 */
interface ArchiveDocumentData {
  /**
   * Page Title field in *Archive*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Archiv
   * - **API ID Path**: archive.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  page_title: prismic.RichTextField;

  /**
   * Japanese Subtitles First field in *Archive*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: archive.japanese_subtitles_first
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  japanese_subtitles_first: prismic.RichTextField;

  /**
   * Japanese Subtitles Second field in *Archive*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: archive.japanese_subtitles_second
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  japanese_subtitles_second: prismic.RichTextField;

  /**
   * Slice Zone field in *Archive*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: archive.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ArchiveDocumentDataSlicesSlice>; /**
   * Meta Title field in *Archive*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: archive.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Archive*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: archive.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Archive*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: archive.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Archive document from Prismic
 *
 * - **API ID**: `archive`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArchiveDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArchiveDocumentData>,
    "archive",
    Lang
  >;

type EventDocumentDataSlicesSlice = never;

/**
 * Content for Event documents
 */
interface EventDocumentData {
  /**
   * Event Title field in *Event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.event_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  event_title: prismic.RichTextField;

  /**
   * Eventfrog Link field in *Event*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Kein Text notwendig
   * - **API ID Path**: event.eventfrog_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  eventfrog_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Event Image field in *Event*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.event_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  event_image: prismic.ImageField<never>;

  /**
   * Event Start Date field in *Event*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: event.event_start_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/timestamp
   */
  event_start_date: prismic.TimestampField;

  /**
   * Event End Date field in *Event*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: event.event_end_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/timestamp
   */
  event_end_date: prismic.TimestampField;

  /**
   * Event Location field in *Event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Miake Izakaya
   * - **API ID Path**: event.event_location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  event_location: prismic.RichTextField;

  /**
   * Event Street field in *Event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Sempacherstrasse 153
   * - **API ID Path**: event.event_street
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  event_street: prismic.RichTextField;

  /**
   * Event Postcode and City field in *Event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: CH - 4053 Basel
   * - **API ID Path**: event.event_postcode_and_city
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  event_postcode_and_city: prismic.RichTextField;

  /**
   * Event Description field in *Event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Text für Event
   * - **API ID Path**: event.event_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  event_description: prismic.RichTextField;

  /**
   * Is Food field in *Event*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: event.is_food
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_food: prismic.BooleanField;

  /**
   * Is Drinks field in *Event*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: event.is_drinks
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_drinks: prismic.BooleanField;

  /**
   * Is Music field in *Event*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: event.is_music
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_music: prismic.BooleanField;

  /**
   * Is Lecture field in *Event*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: event.is_lecture
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_lecture: prismic.BooleanField;

  /**
   * is Art field in *Event*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: event.is_art
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_art: prismic.BooleanField;

  /**
   * Is Crafting field in *Event*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: event.is_crafting
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_crafting: prismic.BooleanField;

  /**
   * Google Location Link field in *Event*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Kein Text
   * - **API ID Path**: event.google_location_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  google_location_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Location Website field in *Event*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Kein Text notwendig
   * - **API ID Path**: event.location_website
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  location_website: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Slice Zone field in *Event*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: event.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<EventDocumentDataSlicesSlice>; /**
   * Meta Title field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: event.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: event.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Event*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Event document from Prismic
 *
 * - **API ID**: `event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<EventDocumentData>, "event", Lang>;

type EventsDocumentDataSlicesSlice = never;

/**
 * Content for Events documents
 */
interface EventsDocumentData {
  /**
   * Page Title field in *Events*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Events
   * - **API ID Path**: events.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  page_title: prismic.RichTextField;

  /**
   * Japanese Subtitles First field in *Events*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: イベント [I|ben|to] --
   * - **API ID Path**: events.japanese_subtitles_first
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  japanese_subtitles_first: prismic.RichTextField;

  /**
   * Japanese Subtitles Second field in *Events*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: eng.: "Event"
   * - **API ID Path**: events.japanese_subtitles_second
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  japanese_subtitles_second: prismic.RichTextField;

  /**
   * Slice Zone field in *Events*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: events.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<EventsDocumentDataSlicesSlice>; /**
   * Meta Title field in *Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: events.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: events.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Events*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: events.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Events document from Prismic
 *
 * - **API ID**: `events`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<EventsDocumentData>, "events", Lang>;

/**
 * Item in *Footer → Socials Links*
 */
export interface FooterDocumentDataSocialsLinksItem {
  /**
   * Socials Link field in *Footer → Socials Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.socials_links[].socials_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  socials_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Socials Icon field in *Footer → Socials Links*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.socials_links[].socials_icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  socials_icon: prismic.ImageField<never>;
}

/**
 * Item in *Footer → Supporters*
 */
export interface FooterDocumentDataSupportersItem {
  /**
   * Supporters Link field in *Footer → Supporters*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.supporters[].supporters_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  supporters_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Supporters Image field in *Footer → Supporters*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.supporters[].supporters_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  supporters_image: prismic.ImageField<never>;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Footer Title field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: KONOMI
   * - **API ID Path**: footer.footer_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer_title: prismic.RichTextField;

  /**
   * Footer Subtitle field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Festival des japanischen Geschmacks
   * - **API ID Path**: footer.footer_subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer_subtitle: prismic.RichTextField;

  /**
   * japanese Subtitle First field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.japanese_subtitle_first
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  japanese_subtitle_first: prismic.RichTextField;

  /**
   * Japanese Subtilte second field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.japanese_subtilte_second
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  japanese_subtilte_second: prismic.RichTextField;

  /**
   * Address Street field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.address_street
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  address_street: prismic.RichTextField;

  /**
   * Address Postcode field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.address_postcode
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  address_postcode: prismic.RichTextField;

  /**
   * Phone Number field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.phone_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  phone_number: prismic.RichTextField;

  /**
   * Socials Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.socials_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  socials_links: prismic.GroupField<
    Simplify<FooterDocumentDataSocialsLinksItem>
  >;

  /**
   * Contact Link Email field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contact_link_email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  contact_link_email: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Supporters Subtitle field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.supporters_subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  supporters_subtitle: prismic.RichTextField;

  /**
   * Supporters field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.supporters[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  supporters: prismic.GroupField<Simplify<FooterDocumentDataSupportersItem>>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Content for Hero Image documents
 */
interface HeroImageDocumentData {
  /**
   * Hero Image field in *Hero Image*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_image.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;
}

/**
 * Hero Image document from Prismic
 *
 * - **API ID**: `hero_image`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeroImageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeroImageDocumentData>,
    "hero_image",
    Lang
  >;

/**
 * Item in *Impressum → Impressum Content*
 */
export interface ImpressumDocumentDataImpressumContentItem {
  /**
   * Subtitle field in *Impressum → Impressum Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impressum.impressum_content[].subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Text field in *Impressum → Impressum Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impressum.impressum_content[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

type ImpressumDocumentDataSlicesSlice = never;

/**
 * Content for Impressum documents
 */
interface ImpressumDocumentData {
  /**
   * Page Title field in *Impressum*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Impressum
   * - **API ID Path**: impressum.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  page_title: prismic.RichTextField;

  /**
   * Impressum Content field in *Impressum*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: impressum.impressum_content[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  impressum_content: prismic.GroupField<
    Simplify<ImpressumDocumentDataImpressumContentItem>
  >;

  /**
   * Slice Zone field in *Impressum*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: impressum.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ImpressumDocumentDataSlicesSlice>; /**
   * Meta Title field in *Impressum*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: impressum.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Impressum*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: impressum.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Impressum*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: impressum.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Impressum document from Prismic
 *
 * - **API ID**: `impressum`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ImpressumDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ImpressumDocumentData>,
    "impressum",
    Lang
  >;

/**
 * Item in *Landing Categories → Categories*
 */
export interface LandingCategoriesDocumentDataCategoriesItem {
  /**
   * Category field in *Landing Categories → Categories*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_categories.categories[].category
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category: prismic.KeyTextField;

  /**
   * Category Key (DO NOT CHANGE!) field in *Landing Categories → Categories*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_categories.categories[].category_key
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category_key: prismic.KeyTextField;
}

/**
 * Content for Landing Categories documents
 */
interface LandingCategoriesDocumentData {
  /**
   * Categories field in *Landing Categories*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_categories.categories[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  categories: prismic.GroupField<
    Simplify<LandingCategoriesDocumentDataCategoriesItem>
  >;
}

/**
 * Landing Categories document from Prismic
 *
 * - **API ID**: `landing_categories`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingCategoriesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LandingCategoriesDocumentData>,
    "landing_categories",
    Lang
  >;

/**
 * Content for Logo documents
 */
interface LogoDocumentData {
  /**
   * Logo Image field in *Logo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo.logo_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo_image: prismic.ImageField<never>;
}

/**
 * Logo document from Prismic
 *
 * - **API ID**: `logo`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LogoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<LogoDocumentData>, "logo", Lang>;

type NewsDocumentDataSlicesSlice = never;

/**
 * Content for News documents
 */
interface NewsDocumentData {
  /**
   * Page title field in *News*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  page_title: prismic.RichTextField;

  /**
   * Japanese Subtitles First field in *News*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.japanese_subtitles_first
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  japanese_subtitles_first: prismic.RichTextField;

  /**
   * Japanese Subtitles Second field in *News*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.japanese_subtitles_second
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  japanese_subtitles_second: prismic.RichTextField;

  /**
   * Slice Zone field in *News*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: news.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<NewsDocumentDataSlicesSlice>; /**
   * Meta Title field in *News*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: news.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *News*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: news.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *News*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * News document from Prismic
 *
 * - **API ID**: `news`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<NewsDocumentData>, "news", Lang>;

/**
 * Item in *Newsarticle → Tags*
 */
export interface NewsarticleDocumentDataTagsItem {
  /**
   * Item field in *Newsarticle → Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsarticle.tags[].item
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  item: prismic.KeyTextField;
}

/**
 * Item in *Newsarticle → Gallery*
 */
export interface NewsarticleDocumentDataGalleryItem {
  /**
   * Gallery Item field in *Newsarticle → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: newsarticle.gallery[].gallery_item
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  gallery_item: prismic.ImageField<never>;
}

type NewsarticleDocumentDataSlicesSlice = never;

/**
 * Content for Newsarticle documents
 */
interface NewsarticleDocumentData {
  /**
   * Tags field in *Newsarticle*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: newsarticle.tags[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tags: prismic.GroupField<Simplify<NewsarticleDocumentDataTagsItem>>;

  /**
   * Title field in *Newsarticle*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsarticle.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Hero Image field in *Newsarticle*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: newsarticle.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Description field in *Newsarticle*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsarticle.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Gallery field in *Newsarticle*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: newsarticle.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  gallery: prismic.GroupField<Simplify<NewsarticleDocumentDataGalleryItem>>;

  /**
   * Slice Zone field in *Newsarticle*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: newsarticle.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<NewsarticleDocumentDataSlicesSlice>; /**
   * Meta Title field in *Newsarticle*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: newsarticle.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Newsarticle*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: newsarticle.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Newsarticle*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: newsarticle.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Newsarticle document from Prismic
 *
 * - **API ID**: `newsarticle`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsarticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NewsarticleDocumentData>,
    "newsarticle",
    Lang
  >;

type PageDocumentDataSlicesSlice = BasicSliceSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Search icon documents
 */
interface SearchIconDocumentData {
  /**
   * Icon field in *Search icon*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: search_icon.icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Search icon document from Prismic
 *
 * - **API ID**: `search_icon`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SearchIconDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SearchIconDocumentData>,
    "search_icon",
    Lang
  >;

/**
 * Item in *Settings → Navigation Items*
 */
export interface SettingsDocumentDataNavigationItemsItem {
  /**
   * Navigation Item field in *Settings → Navigation Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation_items[].navigation_item
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  navigation_item: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Navigation Active Image field in *Settings → Navigation Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation_items[].navigation_active_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  navigation_active_image: prismic.ImageField<never>;

  /**
   * Is Visible in Production field in *Settings → Navigation Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: settings.navigation_items[].is_visible_in_production
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_visible_in_production: prismic.BooleanField;
}

/**
 * Item in *Settings → Navigation Social Icons*
 */
export interface SettingsDocumentDataNavigationSocialIconsItem {
  /**
   * Socials Link field in *Settings → Navigation Social Icons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation_social_icons[].socials_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  socials_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Socials Icon field in *Settings → Navigation Social Icons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation_social_icons[].socials_icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  socials_icon: prismic.ImageField<never>;
}

/**
 * Item in *Settings → Navigation Address*
 */
export interface SettingsDocumentDataNavigationAddressItem {
  /**
   * Address Line field in *Settings → Navigation Address*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation_address[].address_line
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  address_line: prismic.RichTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Page Title field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Konomi
   * - **API ID Path**: settings.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  page_title: prismic.RichTextField;

  /**
   * Page Subtitle Date field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: 30.3 - 5.4.2025
   * - **API ID Path**: settings.page_subtitle_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  page_subtitle_date: prismic.RichTextField;

  /**
   * Navigation Items field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigation_items: prismic.GroupField<
    Simplify<SettingsDocumentDataNavigationItemsItem>
  >;

  /**
   * Navigation Social Icons field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation_social_icons[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigation_social_icons: prismic.GroupField<
    Simplify<SettingsDocumentDataNavigationSocialIconsItem>
  >;

  /**
   * Navigation Address field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation_address[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigation_address: prismic.GroupField<
    Simplify<SettingsDocumentDataNavigationAddressItem>
  >;

  /**
   * Impressum Link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Impressum
   * - **API ID Path**: settings.impressum_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  impressum_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | AboutDocument
  | ArchiveDocument
  | EventDocument
  | EventsDocument
  | FooterDocument
  | HeroImageDocument
  | ImpressumDocument
  | LandingCategoriesDocument
  | LogoDocument
  | NewsDocument
  | NewsarticleDocument
  | PageDocument
  | SearchIconDocument
  | SettingsDocument;

/**
 * Item in *BasicSlice → Schedule → Primary → Event*
 */
export interface BasicSliceSliceSchedulePrimaryEventItem {
  /**
   * Event Name field in *BasicSlice → Schedule → Primary → Event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Sake Trinken
   * - **API ID Path**: basic_slice.schedule.primary.event[].event_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  event_name: prismic.RichTextField;

  /**
   * Event Date field in *BasicSlice → Schedule → Primary → Event*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: basic_slice.schedule.primary.event[].event_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  event_date: prismic.DateField;

  /**
   * Eventfrog Link field in *BasicSlice → Schedule → Primary → Event*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Mehr
   * - **API ID Path**: basic_slice.schedule.primary.event[].eventfrog_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  eventfrog_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *BasicSlice → Default → Primary*
 */
export interface BasicSliceSliceDefaultPrimary {
  /**
   * Heading field in *BasicSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: basic_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Japanese Subtitle First field in *BasicSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: 好み [ko|noː|mi] --
   * - **API ID Path**: basic_slice.default.primary.japanese_subtitle_first
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  japanese_subtitle_first: prismic.RichTextField;

  /**
   * Japanese Subtitles Second field in *BasicSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: dt.: "Geschmack"
   * - **API ID Path**: basic_slice.default.primary.japanese_subtitles_second
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  japanese_subtitles_second: prismic.RichTextField;

  /**
   * Text field in *BasicSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Konomi ist das Festival japanischen Geschmacks in Basel.
   * - **API ID Path**: basic_slice.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Lower Titile field in *BasicSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: 好み... heisst "Geschmack"!
   * - **API ID Path**: basic_slice.default.primary.lower_titile
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  lower_titile: prismic.RichTextField;
}

/**
 * Default variation for BasicSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BasicSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BasicSliceSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *BasicSlice → Schedule → Primary*
 */
export interface BasicSliceSliceSchedulePrimary {
  /**
   * Heading field in *BasicSlice → Schedule → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: basic_slice.schedule.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Japanese Subtitles First field in *BasicSlice → Schedule → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: 食べる [ta|be|ru] --
   * - **API ID Path**: basic_slice.schedule.primary.japanese_subtitles_first
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  japanese_subtitles_first: prismic.RichTextField;

  /**
   * Japanese Subtitle Second field in *BasicSlice → Schedule → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: dt.: "essen"
   * - **API ID Path**: basic_slice.schedule.primary.japanese_subtitle_second
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  japanese_subtitle_second: prismic.RichTextField;

  /**
   * Text field in *BasicSlice → Schedule → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Konomi ist das Festival japanischen Geschmacks in Basel.
   * - **API ID Path**: basic_slice.schedule.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Program Heading field in *BasicSlice → Schedule → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Programm
   * - **API ID Path**: basic_slice.schedule.primary.program_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  program_heading: prismic.RichTextField;

  /**
   * Program text field in *BasicSlice → Schedule → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: In unserem Programm findest du genaue Details über Veranstaltungen
   * - **API ID Path**: basic_slice.schedule.primary.program_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  program_text: prismic.RichTextField;

  /**
   * Event field in *BasicSlice → Schedule → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: basic_slice.schedule.primary.event[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  event: prismic.GroupField<Simplify<BasicSliceSliceSchedulePrimaryEventItem>>;

  /**
   * More Events Link field in *BasicSlice → Schedule → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Mehr Events
   * - **API ID Path**: basic_slice.schedule.primary.more_events_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  more_events_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Schedule variation for BasicSlice Slice
 *
 * - **API ID**: `schedule`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BasicSliceSliceSchedule = prismic.SharedSliceVariation<
  "schedule",
  Simplify<BasicSliceSliceSchedulePrimary>,
  never
>;

/**
 * Primary content in *BasicSlice → Who is Konomi → Primary*
 */
export interface BasicSliceSliceWhoIsKonomiPrimary {
  /**
   * Heading field in *BasicSlice → Who is Konomi → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: basic_slice.whoIsKonomi.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Japanese Subtitles First field in *BasicSlice → Who is Konomi → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: チーム [chi|mu] --
   * - **API ID Path**: basic_slice.whoIsKonomi.primary.japanese_subtitles_first
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  japanese_subtitles_first: prismic.RichTextField;

  /**
   * Japanese Subtitles Second field in *BasicSlice → Who is Konomi → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: dt.: "Team"
   * - **API ID Path**: basic_slice.whoIsKonomi.primary.japanese_subtitles_second
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  japanese_subtitles_second: prismic.RichTextField;

  /**
   * Text field in *BasicSlice → Who is Konomi → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Konomi ist das Festival japanischen Geschmacks in Basel.
   * - **API ID Path**: basic_slice.whoIsKonomi.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Memberpage Link field in *BasicSlice → Who is Konomi → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Erfahren Sie mehr über die Mitglieder
   * - **API ID Path**: basic_slice.whoIsKonomi.primary.memberpage_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  memberpage_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Who is Konomi variation for BasicSlice Slice
 *
 * - **API ID**: `whoIsKonomi`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BasicSliceSliceWhoIsKonomi = prismic.SharedSliceVariation<
  "whoIsKonomi",
  Simplify<BasicSliceSliceWhoIsKonomiPrimary>,
  never
>;

/**
 * Primary content in *BasicSlice → Why Konomi → Primary*
 */
export interface BasicSliceSliceWhyKonomiPrimary {
  /**
   * Heading field in *BasicSlice → Why Konomi → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: basic_slice.whyKonomi.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Japanese Subtitle First field in *BasicSlice → Why Konomi → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: 好み [ko|noː|mi] --
   * - **API ID Path**: basic_slice.whyKonomi.primary.japanese_subtitle_first
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  japanese_subtitle_first: prismic.RichTextField;

  /**
   * Text field in *BasicSlice → Why Konomi → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Konomi ist das Festival japanischen Geschmacks in Basel.
   * - **API ID Path**: basic_slice.whyKonomi.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Last title field in *BasicSlice → Why Konomi → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: 好み [ko|noː|mi] -- dt.: "Geschmack"
   * - **API ID Path**: basic_slice.whyKonomi.primary.last_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  last_title: prismic.RichTextField;

  /**
   * Japanese Subtitles Second field in *BasicSlice → Why Konomi → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: dt.: "Geschmack"
   * - **API ID Path**: basic_slice.whyKonomi.primary.japanese_subtitles_second
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  japanese_subtitles_second: prismic.RichTextField;
}

/**
 * Why Konomi variation for BasicSlice Slice
 *
 * - **API ID**: `whyKonomi`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BasicSliceSliceWhyKonomi = prismic.SharedSliceVariation<
  "whyKonomi",
  Simplify<BasicSliceSliceWhyKonomiPrimary>,
  never
>;

/**
 * Slice variation for *BasicSlice*
 */
type BasicSliceSliceVariation =
  | BasicSliceSliceDefault
  | BasicSliceSliceSchedule
  | BasicSliceSliceWhoIsKonomi
  | BasicSliceSliceWhyKonomi;

/**
 * BasicSlice Shared Slice
 *
 * - **API ID**: `basic_slice`
 * - **Description**: BasicSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BasicSliceSlice = prismic.SharedSlice<
  "basic_slice",
  BasicSliceSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataKonomiMemberItem,
      AboutDocumentDataSlicesSlice,
      ArchiveDocument,
      ArchiveDocumentData,
      ArchiveDocumentDataSlicesSlice,
      EventDocument,
      EventDocumentData,
      EventDocumentDataSlicesSlice,
      EventsDocument,
      EventsDocumentData,
      EventsDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSocialsLinksItem,
      FooterDocumentDataSupportersItem,
      HeroImageDocument,
      HeroImageDocumentData,
      ImpressumDocument,
      ImpressumDocumentData,
      ImpressumDocumentDataImpressumContentItem,
      ImpressumDocumentDataSlicesSlice,
      LandingCategoriesDocument,
      LandingCategoriesDocumentData,
      LandingCategoriesDocumentDataCategoriesItem,
      LogoDocument,
      LogoDocumentData,
      NewsDocument,
      NewsDocumentData,
      NewsDocumentDataSlicesSlice,
      NewsarticleDocument,
      NewsarticleDocumentData,
      NewsarticleDocumentDataTagsItem,
      NewsarticleDocumentDataGalleryItem,
      NewsarticleDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SearchIconDocument,
      SearchIconDocumentData,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItemsItem,
      SettingsDocumentDataNavigationSocialIconsItem,
      SettingsDocumentDataNavigationAddressItem,
      AllDocumentTypes,
      BasicSliceSlice,
      BasicSliceSliceDefaultPrimary,
      BasicSliceSliceSchedulePrimaryEventItem,
      BasicSliceSliceSchedulePrimary,
      BasicSliceSliceWhoIsKonomiPrimary,
      BasicSliceSliceWhyKonomiPrimary,
      BasicSliceSliceVariation,
      BasicSliceSliceDefault,
      BasicSliceSliceSchedule,
      BasicSliceSliceWhoIsKonomi,
      BasicSliceSliceWhyKonomi,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
    };
  }
}
