// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  basic_slice: dynamic(() => import("./BasicSlice")),
  gallery: dynamic(() => import("./Gallery")),
  landing_gallery: dynamic(() => import("./LandingGallery")),
  rich_text: dynamic(() => import("./RichText")),
};
